# Generated by Django 3.2.5 on 2021-07-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210713_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
