# Generated by Django 3.2.5 on 2021-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_borrow_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
