# Generated by Django 3.2.5 on 2021-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_borrow_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
